config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#top"
  get "/" => "users#top"

  resources :users, only:[:show, :edit, :update]
  resources :posts do
  	resources :post_comments, only:[:create, :destroy]
  	resource :favorites, only:[:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	attachment :post_image
	belongs_to :user
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
    end

	validates :title, presence: true ,length: {maximum: 20}
	validates :body, presence: true ,length: {maximum: 100}
	validates :post_image, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true ,length: {maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true ,length: {maximum: 10}
  validates :introduction, length: {maximum: 100}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
  	posts_path
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		post = Post.find(params[:post_id])
		favorite = current_user.favorites.new(post_id: post.id)
		favorite.save
		redirect_to post_path(post)
	end

	def destroy
		post = Post.find(params[:post_id])
		favorite = current_user.favorites.find_by(post_id: post.id)
		favorite.destroy
		redirect_to post_path(post)
	end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def create
		post_comment = PostComment.new(post_comment_params)
		post_comment.user_id = current_user.id
		post = Post.find(params[:post_id])
		post_comment.post_id = post.id
		if post_comment.save
			flash[:notice] = "NEW COMMENT CREATED !"
			redirect_to post_path(post)
		elsif post_comment.comment.empty?
			flash[:comment] = "空白ではコメントできません"
			redirect_to post_path(post)
		else
			flash[:comment] = "コメントは100文字以下までです"
			redirect_to post_path(post)
		end
	end

	def destroy
		post = Post.find(params[:id])
		post_comment = current_user.post_comments.find_by(post_id: post.id)
		post_comment.destroy
		flash[:notice] = "DELETE YOUR COMMENT"
		redirect_to post_path(post)
	end

	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, only:[:edit, :update, :destroy]
	def ensure_correct_user
		@post = Post.find(params[:id])
		if @post.user_id != current_user.id
			redirect_to posts_path
		end
	end

	def index
		@posts = Post.all.order(id: "DESC")
	end

	def show
		@post = Post.find(params[:id])
		@user = User.find(@post.user_id)
		@post_comment = PostComment.new
		@post_comments = @post.post_comments.order(id: "DESC")
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			flash[:notice] = "NEW POST CREATE !"
			redirect_to post_path(@post)
		else
			render("posts/new")
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			flash[:notice] = "UPDATE YOUR POST !"
			redirect_to post_path(@post)
		else
			render("posts/edit")
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	protected
	def post_params
		params.require(:post).permit(:title, :body, :post_image)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only:[:show, :edit, :update]
	before_action :ensure_correct_user, only:[:edit, :update]
	def ensure_correct_user
		@user = User.find(params[:id])
		if current_user != @user
			redirect_to post
		end
	end

	def top
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.order(id: "DESC")
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "UPDATE YOUR PROFILE !"
			redirect_to user_path(@user)
		else
			render("users/edit")
		end
	end

	protected
	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReDeli</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5a4c917e19.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-white bg-white fixed-top">
        <div class="container">
          <%= link_to root_path ,class:"navbar-brand" do %>
              <i class="fas fa-utensils fa-2x" style="color: orange;">
              <span style="font-family: impact">Re:Deli</span></i><% end %>
          <ul class="nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to posts_path, class:"nav-link" do %>
              投稿一覧 <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_post_path, class:"nav-link" do %>
              新規投稿 <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user), class:"nav-link" do %>
              マイページ <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete , class:"nav-link" do %>
              ログアウト<% end %>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to new_user_registration_path ,class:"nav-link" do %>
              新規登録 <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path ,class:"nav-link" do %>
              ログイン <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete , class:"nav-link" do %>
              ログアウト<% end %>
            </li>
            <% end %>
          </ul>
        </div>

      </nav>
    </header>
    <div class="container">
    <%= yield %>
    </div>
    <footer>
      <div class="container">
        <i class="fas fa-utensils" style="color: orange;">
        <span style="font-family: impact">Re:Deli</span></i>
        <p class="top-btn">Go Top</p>
      </div>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-8 offset-lg-2">
			<section class="input-form">
				<% if @post.errors.any? %>
					<div class="alert">
					 <h2><%= @post.errors.count %>errors</h2>
					 <ul>
					  <% @post.errors.full_messages.each do |message| %>
					   <li> <%= message %> </li>
					   <% end %>
					  </ul>
					</div>
				<% end %>

				<h1 style="margin-bottom: 20px"><span>Edit Post</span></h1>
			<%= form_for(@post) do |f| %>
				<div class="field">
					<%= f.label :Post_image, class:"btn btn-primary image-btn" %><br>
					<%= f.attachment_field :post_image , style:"display: none",
						class:"image-select" %>
				</div>
				<div class="field">
					<%= f.label :title %><br>
					<%= f.text_field :title, autofocus: true ,class:"form-control",
						placeholder:"shop_name" %>
				</div>
				<div class="field">
					<%= f.label :body %><br>
					<%= f.text_area :body, autofocus: true ,class:"form-control", rows:"5",
						placeholder:"introduction / review / comment / etc..." %>
				</div>
				<div class="field">
					<%= f.submit "編集", class:"btn btn-warning btn-block" %>
				</div>
			<% end %>
			</section>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<% if flash[:notice] %>
			 	<div class="flash"><%= flash[:notice]%></div>
			<% end %>
			<section class="post-contents">
				<% @posts.each do |post| %>
				<div class="post-content flex">
					<div class="post-image">
						<%= link_to post_path(post) do %>
						<%= attachment_image_tag post, :post_image,
							format:"jpg", class:"image" %>
						<% end %>
					</div>
					<div class="post-main flex">
						<div class="post-profile">
							<%= link_to user_path(post.user) do %>
							<%= attachment_image_tag post.user, :profile_image, format:"jpg",
								size:"100x100",fallback:"no_image.jpg",
								style:"border-radius:50%;" %>
							<% end %>
						</div>
						<div class="post-text">
							<%= link_to post_path(post) do %>
							<i class="fas fa-paw fa-2x"><%= post.title %></i> <% end %><br>
							<div class="post-body">
								<%= post.body%>
							</div>
							<div style="float: right">
								<i class="far fa-comment"><%= post.post_comments.count %></i>
								<i class="fas fa-thumbs-up", style="color:silver;"></i>
								<%= post.favorites.count %>
							</div>
						</div>
					</div>
				</div>
				<% end %>
			</section>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-8 offset-lg-2">
			<section class="input-form">
			<% if @post.errors.any? %>
			<div class="alert">
			 <h2><%= @post.errors.count %>errors</h2>
			 <ul>
			  <% @post.errors.full_messages.each do |message| %>
			   <li> <%= message %> </li>
			   <% end %>
			  </ul>
			</div>
			<% end %>
				<h1 style="margin-bottom: 20px"><span>New Post</span></h1>
				<%= form_for(@post) do |f| %>
					<div class="field">
						<%= f.label :Post_image, class:"btn btn-primary image-btn" %><br>
						<%= f.attachment_field :post_image , style:"display: none",
							class:"image-select" %>
					</div>
					<div class="field">
						<%= f.label :title %><br>
						<%= f.text_field :title, autofocus: true ,class:"form-control",
							placeholder:"shop_name" %>
					</div>
					<div class="field">
						<%= f.label :body %><br>
						<%= f.text_area :body, autofocus: true ,class:"form-control", rows:"5",
							placeholder:"introduction / review / comment / etc..." %>
					</div>
					<div class="field">
						<%= f.submit "送信", class:"btn btn-warning btn-block" %>
					</div>
				<% end %>
			</section>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<% if flash[:notice] %>
			 	<div class="flash"><%= flash[:notice]%></div>
			<% end %>
			<% if flash[:comment] %>
			 	<div class="alert-flash"><%= flash[:comment]%></div>
			<% end %>
			<% if @post_comment.errors.any? %>
				<div class="alert">
				 <h2><%= @post_comment.errors.count %>errors</h2>
				 <ul>
				  <% @post_comment.errors.full_messages.each do |message| %>
				   <li> <%= message %> </li>
				   <% end %>
				  </ul>
				</div>
			<% end %>
			<section class="post-contents">
				<div class="post-content flex">

					<div class="post-image">
						<%= attachment_image_tag @post, :post_image,
							format:"jpg", class:"image" %>
					</div>
					<div class="post-main flex">
						<div class="post-profile">
							<%= link_to user_path(@user) do %>
							<%= attachment_image_tag @user, :profile_image, format:"jpg", size:"100x100",fallback:"no_image.jpg",
								style:"border-radius:50%;" %>
							<% end %><br>
							<% if @user == current_user %>
								<%= link_to edit_post_path(@post) do %>
								<i class="far fa-edit",
									style="padding-right: 5px; margin-top:10px">編集</i><% end %>
								<%= link_to post_path(@post), method: :delete do %>
									<i class="far fa-trash-alt", style="padding-left: 5px">削除</i>
								<% end %>
							<% end %>
						</div>
						<div class="post-text">
							<i class="fas fa-paw fa-2x"><%= @post.title %></i><br>
							<div class="post-body">
								<%= @post.body%>
							</div><br>
							<div style="float: right; margin-top: 10px">
								<i class="far fa-comment"><%= @post.post_comments.count %>件</i>

								<% if @post.favorited_by?(current_user) %>
									<%= link_to post_favorites_path(@post), method: :delete do %>
									<i class="fas fa-thumbs-up", style="color:orange;"></i><% end %>
										<%= @post.favorites.count %>
								<% else %>
									<%= link_to post_favorites_path(@post), method: :post do %>
									<i class="fas fa-thumbs-up", style="color:silver;"></i><% end %>
										<%= @post.favorites.count %>
								<% end %><br>

								<%= @user.name %>  |
								<%= @post.created_at.strftime('%Y/%m/%d') %>
							</div>
						</div>
					</div>
				</div>
			</section>

			<section class="comment-form">
				<h3 style="margin-bottom: 20px"><span>Comments</span></h3>
				<% @post_comments.each do |post_comment| %>
					<div class="comment">
					<div class="comment-image">
						<%= link_to user_path(post_comment.user) do %>
							<%= attachment_image_tag post_comment.user, :profile_image,
								size:"100x100", format:"jpg", fallback:"no_image.jpg",
								style:"border-radius:50%;" %>
						<% end %>
					</div>
					<div class="comment-text">
						<i class="far fa-user"><%= post_comment.user.name %></i><br>
						<%= post_comment.comment %><br>
						<div style="float: right;">
							<%= post_comment.created_at.strftime('%Y/%m/%d') %>|
						<% if current_user == post_comment.user %>
							<%= link_to post_post_comment_path(post_comment), method: :delete do %>
							削除<% end %>
						<% end %>
						</div>
					</div>
					</div>
				<% end %>
			</section>

			<section class="input-form">
				<h3 style="margin-bottom: 20px"><span>New Comment</span></h3>
				<%= form_for [@post, @post_comment] do |f| %>
					<div class="field">
						<%= f.label :comment %><br>
						<%= f.text_area :comment, class:"form-control", rows:"3",
							placeholder:"comment / etc..." %>
					</div>
					<div class="field">
						<%= f.submit "送信", class:"btn btn-warning" %>
					</div>
				<% end %>
			</section>

		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-8 offset-lg-2">
			<section class="input-form">
				<% if @user.errors.any? %>
					<div class="alert">
					 <h2><%= @user.errors.count %>errors</h2>
					 <ul>
					  <% @user.errors.full_messages.each do |message| %>
					   <li> <%= message %> </li>
					   <% end %>
					  </ul>
					</div>
				<% end %>

				<h1 style="margin-bottom: 20px"><span>Edit Profile</span></h1>
			<%= form_for(@user) do |f| %>
				<div class="field">
					<%= f.label :Profile_image, class:"btn btn-primary image-btn" %><br>
					<%= f.attachment_field :profile_image , style:"display: none",
						class:"image-select" %>
				</div>
				<div class="field">
					<%= f.label :name %><br>
					<%= f.text_field :name, autofocus: true ,class:"form-control",
						placeholder:"your_name" %>
				</div>
				<div class="field">
					<%= f.label :introduction %><br>
					<%= f.text_area :introduction, autofocus: true ,class:"form-control",
						rows:"5" %>
				</div>
				<div class="field">
					<%= f.submit "編集", class:"btn btn-warning btn-block" %>
				</div>
			<% end %>
			</section>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<% if flash[:notice] %>
			 	<div class="flash"><%= flash[:notice]%></div>
			<% end %>
			<section>
					<div class="profile-main">
						<div class="profile-image">
							<%= attachment_image_tag @user, :profile_image, format:"jpg", size:"200x200",fallback:"no_image.jpg", style:"border-radius:50%;" %><br>
							<% if @user == current_user %>
								<%= link_to edit_user_path(@user) do %>
								<i class="far fa-edit",
									style="padding-right: 5px; margin-top:10px">編集
								</i><% end %>
							<% end %>
						</div>
						<div class="profile-text">
							<i class="fas fa-dog fa-2x"><%= @user.name %></i><br>
							<div class="post-body">
								<%= @user.introduction %>
							</div>
						</div>
					</div>
		    </section>

			<section class="post-contents">
				<% @posts.each do |post| %>
				<div class="post-content flex">
					<div class="post-image">
						<%= link_to post_path(post) do %>
						<%= attachment_image_tag post, :post_image,
							format:"jpg", class:"image" %>
						<% end %>
					</div>
					<div class="post-main flex">
						<div class="post-text">
							<%= link_to post_path(post) do %>
							<i class="fas fa-paw fa-2x"><%= post.title %></i> <% end %><br>
							<div class="post-body">
								<%= post.body%>
							</div>
						</div>
						<div class="post-profile">
							<div style="float: right; margin-top: 10px">
								comments : <%= post.post_comments.count %>件
								<%= post.created_at.strftime('%Y/%m/%d') %>
							</div>
						</div>
					</div>
				</div>
				<% end %>
			</section>
		</div>
	</div>
</div>

app/views/users/top.html.erb
<div class="top-contents">
	<div class="top1"></div>
	<div class="top2"></div>
	<div class="top3"></div>
	<div class="top4"></div>
	<div class="top5"></div>
	<div class="top7"></div>
</div>

<% if flash[:notice] %>
 	<div class="flash"><%= flash[:notice]%></div>
<% end %>

<section style="margin: 80px 0px">
<% if user_signed_in? %>
<h1>Enjoy to Re:Deli ! ! !</h1>
<% else %>
<h1>Welcome to Re:Deli ! ! !</h1>
<% end %>
<h2>WebSite Introduction...</h2>
<div class="row" style="margin-top: 40px">
	<div class="col-lg-10 offset-lg-1">
	<span>
		<i class="fas fa-coffee fa-5x"></i>
		<i class="fas fa-long-arrow-alt-right fa-3x">　</i>
		<i class="fas fa-hamburger fa-5x"></i>
		<i class="fas fa-long-arrow-alt-right fa-3x">　</i>
		<i class="fas fa-ice-cream fa-5x"></i>
		<i class="fas fa-long-arrow-alt-right fa-3x">　</i>
		<i class="fas fa-beer fa-5x"></i>
		<i class="fas fa-long-arrow-alt-right fa-3x">　</i>
		<i class="far fa-laugh-squint fa-5x"></i>
	</span>
	</div>
</div>
</section>